[package]
name = "PathOfBuilding"
version = "2.34.1"
edition = "2021"

[[bin]]
bench = false
path = "evloop/main.rs"
name = "path-of-building"

[dependencies]
mlua = { version = "0.9.1", features = ["luajit", "vendored"] }
