[package]
name = "PathOfBuilding"
version = "2.34.1"
edition = "2021"

[[bin]]
bench = false
path = "evloop/main.rs"
name = "path-of-building"

[dependencies]
rlua = { version = "0.19.7", default-features = false, features = ["system-luajit"] }
